### ISSUE TITLE
slimJar task does not include slimjar.json or slimjar-resolutions.json files in CI/CD (Github and Jenkins)

### ISSUE THREAD

**Issue by Thatsmusic99** [DaRacci/slimjar#17]
Hello! I hope you're staying well.

I've been trying to use slimjar in my CI/CD processes, but the resulting jar from both GitHub Actions and Jenkins seems to be missing the slimjar JSON files, the jar file in downloads coming from [here](https://github.com/Niestrat99/AT-Rewritten/actions/runs/5453184353?pr=107):

![image](https://github.com/DaRacci/slimjar/assets/25277367/3cea1611-bfc0-48fd-b385-262a482259c3)

Whilst I am building with JBR 17 on Windows 11 on my main PC, the Github action provided uses Temurin 17 on Ubuntu 22.04.2. There's a bit more detail in the GitHub Action itself. Slimjar v1.5.4 should be in use. 

Is there something wrong with what I'm doing?

**Comment by DaRacci** [comment]
Hey sorry i seem to have somehow missed seeing this, try adding this into your build file: ```kotlin
tasks.shadowJar {
    from(tasks.slimJar.outputDirectory)
}```

I'll eventually finish version 2 which will fix this, but i just don't have the time for it currently

**Comment by Thatsmusic99** [comment]
Hey, it's fine, no worries! I've been busy myself.

It helps on the second run in my environment which is an improvement, since the files are already in the slimjar folder. However, when generating the files for the first time or after deleting them, they are not included in the final jar, which is the main issue I'm having.

**Comment by DaRacci** [comment]
might be a issue with task dependency, is your ci running something that isn't the standard build tasks, if so try adding a dependson for slimjar

**Comment by Thatsmusic99** [comment]
Nope, just running slimJar. From the latest run: https://github.com/Niestrat99/AT-Rewritten/actions/runs/5811268286/job/15754103179
![image](https://github.com/DaRacci/slimjar/assets/25277367/0fd11343-44cf-4a5a-8cdf-c4e278ec8b23)

**Comment by DaRacci** [comment]
I'll be honest i really have no clue.
That latest run seems to be working so is it just that other ci task that wasnt?

**Comment by Thatsmusic99** [comment]
As in the jar file runs? That would be because I added an extra task to force in the JSON files after the build finishes:
![image](https://github.com/DaRacci/slimjar/assets/25277367/dbbbcd5e-c47b-4816-9af6-caba00a7e3dd)

It's really weird, the isolated jar gets added to the final build, but doesn't end up in any of the resources folders, I thought it would've been but it doesn't seem like it.

**Comment by DaRacci** [comment]
Ah I see, I'll do some messing around later to see if I'm able to find anything, not too confident in my java/gradle anymore though, haven't written in over half a year since I moved to rust.

**Comment by Thatsmusic99** [comment]
So I did take a poke around Slimjar and fixed the bug by making shadowJar run after slimJar, so slimJar targets the jar task rather than shadowJar (and most likely avoids reobfJar too). Do you think that would result in any breaking changes or such? 

[The commit for it ended up being a lot more straightforward than I imagined](https://github.com/Thatsmusic99/slimjar/commit/00cf7102fdbcfbf02ce6fb73ca3ff463a7723b04), do you want me to open a PR with it?

**Comment by DaRacci** [comment]
I believe there was a specific reason for that order, but if its picking up the shadowJar task even as it runs after i think that will work for the reobf too, please make the pr and ill merge it, ill do some testing with a reobf task at some point and see if that works too, sorry for basically forgetting to look into it, been swamped with work.

**Comment by Thatsmusic99** [comment]
It's fine, don't worry, figured that would be the case so wanted to take some of the load off from you. 😄

**Comment by DaRacci** [comment]
version 1.6.1 has being published and pushed to the gradle repos
